[package]
name = "pusheventhub"
version = "0.1.0"
authors = ["Francesco Cogno <francesco.cogno@outlook.com>"]

[dependencies]
clap="*"
log="*"
env_logger = "*"
hyper="*"
url = "*"
chrono = "*"
time="*"
rust-crypto="*"
rustc-serialize="*"
